---
    - name: Repartition drive
      block:
        - name: Wipe install drive and all its partitions
          command: find /dev -wholename "{{ target_drive }}*" -exec wipefs --force --all {} \;
          tags:
            - wipefs
        - name: Create boot partition
          parted:
            device: '{{ target_drive }}'
            label: gpt
            number: 1
            part_end: 512MB
            name: boot
            flags: [boot, esp]
            state: present
        - name: Create root partition
          parted:
            device: '{{ target_drive }}'
            label: gpt
            number: 2
            part_start: 512MB
            name: root
            flags: [lvm]
            state: present
      tags:
        - repartition
    - include: tasks/Generic/Install/New_LVM.yml
